version: '2'
services:
    cooperapp-app:
        image: cooperapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@cooperapp-oracle:1521:cooperApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8181:8181
